### ISSUE TITLE
Pause/Play inoperable after USB update

### ISSUE THREAD

**Issue by IanColquhoun** [ColquhounAudio/AxiomBuild#28]
It actually works once but then becomes inoperable.

**Comment by ggiraudon** [comment]
Added a one liner patch for that one.
The cause for the issue is a bit obscure and I'm trying to reach Michelangelo about it.
It has to do with the fact that while the playback is handled by mpd, the service for playing webradio registers as "webradio" in the state machine.
This in turn causes update from MPD to be discarded when they should be valid for webradio too.
